<?php
/**
9K SPOTTER 404 PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>
<html>
	<head>
		<title>404 Page Not Found</title>
		<meta name="viewport" content="width=device-width">
		<link rel="stylesheet" href="/Code9000/styles/index.css">
	</head>
	<body>
		<h1>Ooops.</h1>
		<img class='sloth404' src="/Code9000/img/404sloth.png" alt="404 sloth"/>
		<p class='big'><strong>404 Page Not Found</strong></p>
		<p class='big'>Oops. Our friendly server sloth couldn't locate the file.</p>
		<p><a href='/Code9000'>Maybe go back home?</a></p>
	</body>
</html>