<?php
/**
9K SPOTTER 404 PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>
<html>
	<head>
		<title>404 Page Not Found</title>
		<!-- LINK MY OWN STYLESHEET -->
		<link rel="stylesheet" href="/Code9000/styles/index.css">
	</head>
	<body>
		<h1>404 Page Not Found</h1>
		<p>Oops. This page was not found.</p>
	</body>
</html>