<?php
/**
9K SPOTTER ACCOUNT PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>
	<?php
		echo($this->render('header.phtml'));
	?>
	<div class="row">
		<div>
			<h1>Your account</h1>
			<?php if (isset($this->data['user'])): ?>
			<h2><?php echo $this->data['user']['firstname'] . " " . $this->data['user']['surname'] ?></h2>
			<div class='row'>
			<div class="two columns image circle center">
				<img src="<?php echo  "http://" . $_SERVER['HTTP_HOST'] . "/" . $this->data['user']['avatar']?>" />
			</div>
			<div class='eight columns'>
				
				<p>Email: <?php echo $this->data['user']['email']?></p>
				<p>Born: <?php echo $this->data['user']['dateofbirth']?></p>
				<p>Joined: <?php echo $this->data['user']['createddate']?></p>
				<p>Last time you logged in: <?php echo $this->data['user']['lastloggedindate']?></p>
				<ul>
					<li><div class="medium btn primary"><a href="/code9000/account/edit" >Edit your details</a></div></li>
					<li><div class="medium btn primary"><a href="/Code9000/logout">Log out</a></div></li>
				</ul>
			</div>
			</div>
			<?php endif;?>
		</div>
		</div>
		<footer class='row'>
			<p><a href='http://okfn.be/'>&copy; 2013 OKFN</a>. Some rights reserved. <a href='#'>Developed by 9K.</a></p>
		</footer>
	</div>

	<!-- Grab Google CDN's jQuery, fall back to local if offline -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="scripts/libs/jquery-1.9.1.min.js"><\/script>')</script>

  <!--
  Include gumby.js followed by UI modules.
  Or concatenate and minify into a single file
  <script src="scripts/libs/gumby.js"></script>
  <script src="scripts/libs/ui/gumby.retina.js"></script>
  <script src="scripts/libs/ui/gumby.fixed.js"></script>
  <script src="scripts/libs/ui/gumby.skiplink.js"></script>
  <script src="scripts/libs/ui/gumby.toggleswitch.js"></script>
  <script src="scripts/libs/ui/gumby.checkbox.js"></script>
  <script src="scripts/libs/ui/gumby.radiobtn.js"></script>
  <script src="scripts/libs/ui/gumby.tabs.js"></script>
  <script src="scripts/libs/ui/gumby.navbar.js"></script>
  <script src="scripts/libs/ui/jquery.validation.js"></script>
  <script src="scripts/libs/gumby.init.js"></script>-->

  <script src="scripts/libs/gumby.min.js"></script>
  <script src="scripts/plugins.js"></script>
  <script src="scripts/main.js"></script>

  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->

  </body>
</html>