<?php
/**
9K SPOTTER ACCOUNT delete
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Stefaan Christiaens (stefaan.ch@gmail.com)
*/
?>
<?php
		echo $this->render('header.phtml');
?>
	<div class="row">
    <h1>Delete Profile</h1>
    <input type="button" value="Delete profile" onclick="deleteProfile()" />
    <input type="button" onclick="location='/code9000/account'" value="cancel" />
</div>
<!-- BOTTOM SCRIPTS -->
<!-- 1. GRAB GOOGLE'S JQUERY CDN -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- 2. FALLBACK TO LOCAL JQUERY IF CDN NOT ACTIVE -->
<script>window.jQuery || document.write('<script src="_scripts/libs/jquery-2.0.2.js"><\/script>')</script>
<script>
    var _deleteProfilePath = "http://" + window.location.host.toString() + "/Code9000/account/delete";
    function deleteProfile()
    {
        if(confirm('Are you sure?'))
        {
             $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                cache: false,
                data: {"delete":1},
                url: _deleteProfilePath,
                success: function(json){
                    window.location = "http://" + window.location.host.toString() + "/Code9000/logout";
                }
            });
        }
    }
    
</script>
</body>
</html>
