<?php
/**
9K SPOTTER ACCOUNT PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>
	<?php
		echo($this->render('header.phtml'));	

	?>

	<div class="row">
		<div>
			<h1>Your account</h1>
			<?php if (isset($this->data['user'])): ?>
			<h2><?php echo $this->data['user']['firstname'] . " " . $this->data['user']['surname'] ?></h2>
			<div class='row'>
			<div class="two columns image circle center">
				<img src="<?php echo  "http://" . $_SERVER['HTTP_HOST'] . "/Code9000/uploads/" . $this->data['user']['avatar']?>" />
			</div>
			<div class='eight columns'>
				
				<p>Email: <?php echo $this->data['user']['email']?></p>
				<p>Born: <?php echo $this->data['user']['dateofbirth']?></p>
				<p>Joined: <?php echo $this->data['user']['createddate']?></p>
				<p>Last time you logged in: <?php echo $this->data['user']['lastloggedindate']?></p>
				<ul>
					<li><div class="medium btn primary"><a href="/code9000/account/edit" >Edit your details</a></div></li>
					<li><div class="medium btn primary"><a href="/Code9000/logout">Log out</a></div></li>
				</ul>
			</div>
			</div>
			<?php endif;?>
		</div>
		</div>
		<footer class='row'>
			<p><a href='http://okfn.be/'>&copy; 2013 OKFN</a>. Some rights reserved. <a href='#'>Developed by 9K.</a></p>
		</footer>
	</div>

	<?php echo $this->render('libsfooter.phtml') ?>

  </body>
</html>