<?php
/**
9K SPOTTER ACCOUNT delete
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Stefaan Christiaens (stefaan.ch@gmail.com)
*/
?>
<!doctype html>
<html dir="ltr" lang="nl-be">
    <head>
        <!-- CHARACTER ENCODING -->
        <meta charset="UTF-8">
        <!-- LATEST VERSION OF RENDERING ENGINE -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <!-- MOST IMPORTANT SEO FRIENDLY TAG -->
        <title>account delete 9K</title>
        <!-- OTHER IMPORTANT SEO TAGS -->
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="author" content="">
        <meta name="copyright" content="">
        <!-- HUMANS.TXT FILE -->
        <link rel="author" type="text/plain" href="humans.txt">
        <!-- MOBILE VIEWPORT -->
        <meta name="viewport" content="width=device-width">
        <!-- LINK MY OWN STYLESHEET -->
        <link rel="stylesheet" href="/Code9000/styles/index.css">
    </head>
<body>
<!-- LAYOUT / TYPO / CONTENT -->
<div id="page-wrapper" class="page">
    <h1>Delete Profile</h1>
    <input type="button" value="Delete profile" onclick="deleteProfile()" />
    <input type="button" onclick="location='/code9000/account'" value="cancel" />
</div>


<!-- BOTTOM SCRIPTS -->
<!-- 1. GRAB GOOGLE'S JQUERY CDN -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- 2. FALLBACK TO LOCAL JQUERY IF CDN NOT ACTIVE -->
<script>window.jQuery || document.write('<script src="_scripts/libs/jquery-2.0.2.js"><\/script>')</script>
<script>
    var _deleteProfilePath = "http://" + window.location.host.toString() + "/Code9000/account/delete";
    function deleteProfile()
    {
        if(confirm('Are you sure?'))
        {
             $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                cache: false,
                data: {"delete":1},
                url: _deleteProfilePath,
                success: function(json){
                    window.location = "http://" + window.location.host.toString() + "/Code9000/logout";
                }
            });
        }
    }
    
</script>
</body>
</html>
