<?php
/**
9K SPOTTER ACCOUNT delete
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Stefaan Christiaens (stefaan.ch@gmail.com)
*/
?>
<?php
		echo $this->render('header.phtml');
?>
	<div class="row">
    <h1>Delete Profile</h1>
    <input type="button" value="Delete profile" onclick="deleteProfile()" />
    <input type="button" onclick="location='/code9000/account'" value="cancel" />
</div>
<?php echo $this->render('libsfooter.phtml') ?>
<script>
    var _deleteProfilePath = "http://" + window.location.host.toString() + "/Code9000/account/delete";
    function deleteProfile()
    {
        if(confirm('Are you sure?'))
        {
             $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                cache: false,
                data: {"delete":1},
                url: _deleteProfilePath,
                success: function(json){
                    window.location = "http://" + window.location.host.toString() + "/Code9000/logout";
                }
            });
        }
    }
    
</script>
</body>
</html>
