<?php
/**
9K SPOTTER ACCOUNT PAGE edit
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Stefaan Christiaens (stefaan.ch@gmail.com)
*/
?>
<?php
		echo $this->render('header.phtml');
?>
	<div id="container" class="row">
    <h1>edit Profile</h1>
<?php if (isset($this->data['user'])): ?>
    <form method="POST">
                        <div class="row xwide valign">
                                        <ul class="seven columns centered">
                                            <li class="field prepend">
                                                <span class="adjoined"><i class="icon-user"></i></span>
                                                <input class=" input" type="text" placeholder="First Name" value = "<?php echo $this->data['user']['firstname']?>" name="firstname" id="firstname" />
                                            </li>
                                            <li class="field prepend">
                                                <span class="adjoined"></span>
                                                <input class=" input" type="text" placeholder="Surname" name="surname" id="surname" value="<?php echo $this->data['user']['surname']?>" />
                                            </li>
                                            <li class="field prepend">
                                                <span class="adjoined"><i class="icon-mail"></i></span>
                                                <input class="email input" type="email" placeholder="Email" name="email" id="email" value="<?php echo $this->data['user']['email']?>" />
                                            </li>
                                            <li class="field prepend">
                                                <span class="adjoined"><i class="icon-calendar"></i></span>
                                                <input class="date input" type="date" placeholder="Date of Birth" name="dateofbirth" id="dateofbirth" value="<?php echo explode(" ", $this->data['user']['dateofbirth'])[0]?>" />
                                            </li>
                                            <li class="field prepend">
                                                <span class="adjoined"><i class="icon-lock"></i></span>
                                                <input class="password input" type="password" placeholder="New Password" id="newpassword" name="newpassword" />
                                            </li>
                                            <li class="field prepend">
                                                <span class="adjoined"></span>
                                                <input class="password input" type="password" placeholder="Retype new password" name="newpassword_r" id="newpassword_r" />
                                            </li>
                                            <li class="field prepend">
                                                <span class="adjoined"><i class="icon-lock-open"></i></span>
                                                <input class="password input" type="password" placeholder="Old Password" id="oldpassword" name="oldpassword" />
                                            </li>
                                            <li class="field">
                                                <img src="<?php echo  "http://" . $_SERVER['HTTP_HOST'] . "/" . $this->data['user']['avatar']?>">
                                            </li>
                                            <li class="field prepend">
                                                <span class="adjoined"><i class="icon-camera"></i></span>
                                                <label id="fileButton" class="medium primary btn" for="file">Set Avatar...</label>
                                                <input class="file input" type="file" value="change Avatar" id="file" name="file" />
                                            </li>
                                            <li class="field">
                                                <div id="avatar"></div>
                                            </li>
                                            <li class="field">
                                            <li class="field">
                                                <label class="checkbox checked" for="admin">
                                                    <input name="admin" id="admin" value="1" type="checkbox" >
                                                    <span></span> Admin
                                                </label>
                                            </li>


                                            <li class="field">
                                                <div class="medium primary btn" style="width: 100%"><input type="submit" value="Edit"></div>
                                                <div class="medium primary btn" style="width: 100%"><input type="submit" onclick="location='/code9000/account'" value="cancel" value="Cancel"></div>

                                            </li>
                                        </ul>
                                    </div>

    </form>
    <div class="small primary btn" style="width: 100%"><a href="/code9000/account/delete">Delete profile</a></div>
    <a href="/code9000/account/delete">Delete profile</a>
<?php endif;?>
</div>


<!-- BOTTOM SCRIPTS -->
<!-- 1. GRAB GOOGLE'S JQUERY CDN -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- 2. FALLBACK TO LOCAL JQUERY IF CDN NOT ACTIVE -->
<script>window.jQuery || document.write('<script src="_scripts/libs/jquery-2.0.2.js"><\/script>')</script>
<script src="/Code9000/scripts/avatarupload.js"></script>
</body>
</html>
