<?php
/**
9K SPOTTER ABOUT PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
Stefaan Christiaens (stefaan.ch@gmail.com)
*/
?>
<!doctype html>
<html dir="ltr" lang="nl-be">
    <head>
        <!-- CHARACTER ENCODING -->
        <meta charset="UTF-8">
        <!-- LATEST VERSION OF RENDERING ENGINE -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <!-- MOST IMPORTANT SEO FRIENDLY TAG -->
        <title>9KBuilder | API</title>
        <!-- OTHER IMPORTANT SEO TAGS -->
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="author" content="Stefaan Christiaens">
        <meta name="copyright" content="">
        <!-- HUMANS.TXT FILE -->
        <link rel="author" type="text/plain" href="humans.txt">
        <!-- MOBILE VIEWPORT -->
        <meta name="viewport" content="width=device-width">
        <!-- LINK MY OWN STYLESHEET -->
        <link rel="stylesheet" href="/Code9000/styles/index.css">
    </head>
<body>
<!-- LAYOUT / TYPO / CONTENT -->
<div id="page-wrapper" class="page">
    <nav>
        <ul>
            <li><a href='/Code9000/home'>Home</a></li>
            <li><a href='/Code9000/alerts'>Meldingen</a></li>
            <li><a href='/Code9000/tips'>Tips</a></li>
            <li><a href='/Code9000/about'>Over deze app</a></li>
        </ul>
    </nav>
    <h1>9K Spotter</h1>
    <section>
        <p>9K Spotter was made available by:</p>
        <ul>
            <li>Stefaan Christiaens</li>
            <li>Nico Verbruggen</li>
            <li>Robbe Anckaert</li>
            <li>Tom Van humbeek</li>
            <li>OKFN Belgium</li>
            <li>open Summer of code</li>
            <li>AppsForGhent</li>
            <li>Digipolis</li>
        </ul>
    </section>
</div>

<h2>9KBuilder API</h2>
<hr />
<ul>
    <li><a href="/Code9000/api/spots">spots</a></li>
    <li><a href="/Code9000/api/comments">comments</a></li> 
    <li><a href="/Code9000/api/cityprojects">cityprojects</a></li>
    <li><a href="/Code9000/api/cityproposals">cityproposals</a></li>
    <li><a href="/Code9000/api/locations">locations</a></li>
    <li><a href="/Code9000/api/photos">photos</a></li>
    <li><a href="/Code9000/api/users">users</a></li>
</ul>
<!-- BOTTOM SCRIPTS -->
<!-- 1. GRAB GOOGLE'S JQUERY CDN -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- 2. FALLBACK TO LOCAL JQUERY IF CDN NOT ACTIVE -->
<script>window.jQuery || document.write('<script src="_scripts/libs/jquery-2.0.2.js"><\/script>')</script>
</body>
</html>
