<?php
/**
9K SPOTTER ABOUT PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
Stefaan Christiaens (stefaan.ch@gmail.com)
*/
?>
<?php
		echo $this->render('header.phtml');
?>
	<div class="row">		
		<h1 class='h_und'>About 9K Spotter</h1>
		<div class="row">
			<div class='twelve columns breathe'>
                <h2>9KBuilder API</h2>
                <h3 class="italic uppercase negative">Get information</h3>
                <p>Using GET, you can get (excuse the pun) data from our application.</p>
            </div>
		</div>
        <div class='twelve columns breathe'>
            <ul class="borderBtm">
                <li class="italic uppercase borderTop">Locations</li>
            <ul class="breathe">
                <li><a href="/Code9000/api/locations">locations</a></li>
                <li><a href="/Code9000/api/locations/1">specific location</a></li>
                <li><a href="/Code9000/api/locations/last15">last 15 locations</a></li>
            </ul>
            <li class="italic uppercase borderTop">Spots</li>
            <ul class="breathe">
                <li><a href="/Code9000/api/spots">get all spots</a></li>
                <li><a href="/Code9000/api/spots/1">one specific spot</a></li>
                <li><a href="/Code9000/api/locations/1/spots">get all spots for one specific location</a></li>
            </ul>
            <li class="italic uppercase borderTop">Comments</li>
            <ul class="breathe">
                <li><a href="/Code9000/api/comments">get all comments</a></li>
                <li><a href="/Code9000/api/comments/1">get one specific comment</a></li>
                <li><a href="/Code9000/api/users/1/comments">get all comments for one specific user</a></li>
            </ul>
            <li class="italic uppercase borderTop">Pictures</li>
            <ul class="breathe">
                <li><a href="/Code9000/api/photos">photos</a></li>
                <li><a href="/Code9000/api/photos/1">specific photo</a></li>
                <li><a href="/Code9000/api/photos/last15">last 15 photos</a></li>
            </ul>
            <li class="italic uppercase borderTop">City Projects &amp; Proposals</li>
            <ul class="breathe">
            <li><a href="/Code9000/api/cityprojects">cityprojects</a></li>
            <li><a href="/Code9000/api/cityproposals">cityproposals</a></li>
            </ul>
        </ul>
        <p class="borderTop">The following information requires you to log in with your account. If you are not an administrator, you cannot get this information or get limited information.</p>
        <ul class="breathe">
            <li><a href="/Code9000/api/users">users*</a></li>
            <li><a href="/Code9000/api/users/1">user with a specific ID**</a></li>
        </ul>
        <h3 class="italic uppercase negative">Legend</h3>
        <ul class="breathe">
            <li>* (not accessible without admin rights)</li>
            <li>** (accessible without admin rights, gives limited information</li>
        </ul>
    </div>
</div>
<!-- BOTTOM SCRIPTS -->
<!-- 1. GRAB GOOGLE'S JQUERY CDN -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- 2. FALLBACK TO LOCAL JQUERY IF CDN NOT ACTIVE -->
<script>window.jQuery || document.write('<script src="_scripts/libs/jquery-2.0.2.js"><\/script>')</script>
</body>
</html>
