<?php
/**
9K SPOTTER ABOUT PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
Stefaan Christiaens (stefaan.ch@gmail.com)
*/
?>
<!doctype html>
<html dir="ltr" lang="nl-be">
    <head>
        <!-- CHARACTER ENCODING -->
        <meta charset="UTF-8">
        <!-- LATEST VERSION OF RENDERING ENGINE -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <!-- MOST IMPORTANT SEO FRIENDLY TAG -->
        <title>9KBuilder | API</title>
        <!-- OTHER IMPORTANT SEO TAGS -->
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="author" content="Stefaan Christiaens">
        <meta name="copyright" content="">
        <!-- HUMANS.TXT FILE -->
        <link rel="author" type="text/plain" href="humans.txt">
        <!-- MOBILE VIEWPORT -->
        <meta name="viewport" content="width=device-width">
        <!-- LINK MY OWN STYLESHEET -->
        <link rel="stylesheet" href="/Code9000/styles/index.css">
    </head>
<body>
<!-- LAYOUT / TYPO / CONTENT -->
<div id="page-wrapper" class="page">
    <nav>
        <ul>
            <li><a href='/Code9000/home'>Home</a></li>
            <li><a href='/Code9000/alerts'>Meldingen</a></li>
            <li><a href='/Code9000/tips'>Tips</a></li>
            <li><a href='/Code9000/about'>Over deze app</a></li>
        </ul>
    </nav>
    <h2>9KBuilder API</h2>
<hr />
<h3>Get information</h3>
<p>Using GET, you can get (excuse the pun) data from our application.</p>
<ul>
	<li>Locations</li>
	<ul>
		<li><a href="/Code9000/api/locations">locations</a></li>
		<li><a href="/Code9000/api/locations/1">specific location</a></li>
		<li><a href="/Code9000/api/locations/last15">last 15 locations</a></li>
	</ul>
	<li>Spots</li>
	<ul>
		<li><a href="/Code9000/api/spots">get all spots</a></li>
		<li><a href="/Code9000/api/spots/1">one specific spot</a></li>
		<li><a href="/Code9000/api/locations/1/spots">get all spots for one specific location</a></li>
	</ul>
	<li>Comments</li>
	<ul>
		<li><a href="/Code9000/api/comments">get all comments</a></li>
		<li><a href="/Code9000/api/comments/1">get one specific comment</a></li>
		<li><a href="/Code9000/api/users/1/comments">get all comments for one specific user</a></li>
	</ul>
	<li>Pictures</li>
	<ul>
		<li><a href="/Code9000/api/photos">photos</a></li>
		<li><a href="/Code9000/api/photos/1">specific photo</a></li>
		<li><a href="/Code9000/api/photos/last15">last 15 photos</a></li>
	</ul>
	<li>City Projects &amp; Proposals</li>
	<ul>
    <li><a href="/Code9000/api/cityprojects">cityprojects</a></li>
    <li><a href="/Code9000/api/cityproposals">cityproposals</a></li>
	</ul>
</ul>
<p>The following information requires you to log in with your account. If you are not an administrator, you cannot get this information or get limited information.</p>
<ul>
	<li><a href="/Code9000/api/users">users*</a></li>
	<li><a href="/Code9000/api/users/1">user with a specific ID**</a></li>
</ul>
<h3>Legend</h3>
<ul>
	<li>* (not accessible without admin rights)</li>
	<li>** (accessible without admin rights, gives limited information</li>
</ul>
</div>
<!-- BOTTOM SCRIPTS -->
<!-- 1. GRAB GOOGLE'S JQUERY CDN -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- 2. FALLBACK TO LOCAL JQUERY IF CDN NOT ACTIVE -->
<script>window.jQuery || document.write('<script src="_scripts/libs/jquery-2.0.2.js"><\/script>')</script>
</body>
</html>
