<?php
/**
9K SPOTTER CITYPOPOSALS PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Stefaan Christiaens @stefchri (stefaan.ch@gmail.com)
*/
?>
	<?php
		echo($this->render('header.phtml'));
	?>
		<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.css" />
		<div class='row'>
			<div id="map"></div>
            <section id="prop_content">
				<h1 id="prop_name">Current and future projects in Ghent</h1>
			</section>
		</div>

		<footer class='row'>
			<p><a href='http://okfn.be/'>&copy; 2013 OKFN</a>. Some rights reserved. <a href='http://www.twitter.com/9Kspotter'>Developed by 9K.</a></p>
		</footer>
	</div>
	<script>
	    var prop_id = <?php echo $this->data['id'] ?>;
	    var _user = <?php echo $this->data['user'] ?>;
	</script>
	<script src="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.js"></script>
<?php echo $this->render('libsfooter.phtml') ?>
  <script src="/Code9000/scripts/cityprop.js"></script>
	</body>
</html>