<?php
/**
9K SPOTTER SPOTTINGS PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>
	<?php
		echo($this->render('header.phtml'));
	?>
		<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.css" />
		<div class='row'>
				<h1>Current and future projects in Ghent</h1>
				<a href="#mapbutton" id="mapbutton">Show map</a>
				<a href="#listbutton" id="listbutton">Show list</a>
				<section id="spotlist">
					
				</section>
				<section id="spotmap">
					<div id="map"></div>
				</section>
				<p></p>
		</div>
		<footer class='row'>
			<p><a href='http://okfn.be/'>&copy; 2013 OKFN</a>. Some rights reserved. <a href='#'>Developed by 9K.</a></p>
		</footer>
	</div>

	<?php echo $this->render('libsfooter.phtml') ?>
  <script src="scripts/cityprops_all.js"></script>

 
	<style>
		#map{
			height:500px !important;
			width: 100% !important;
		}
	</style>
  
	</body>
</html>