<?php
/**
9K SPOTTER ERROR PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>

	<?php
		echo($this->render('header.phtml'));
	?>

	<div class="row">
		<div class='center'>
		<h2>Oh no.</h2>
		<div class="row">
			<div class='twelve columns breathe'>
				<img class='sloth404' src="/Code9000/img/404sloth.png" alt="404 sloth"/>
				<h3>I think you just broke the site doing that</h3>
				<p class='large'>Our friendly server sloth just noticed that something broke the site. We're sorry. <a href="/Code9000/">Return to the homepage.</a></p>
				<ul>
					<li class='danger label'>An error has occurred.</li>
				</ul>
			</div>
		</div>	
		</div>
		<footer class='row'>
			<p><a href='http://okfn.be/'>&copy; 2013 OKFN</a>. Some rights reserved. <a href='#'>Developed by 9K.</a></p>
		</footer>
	</div>

	<?php echo $this->render('libsfooter.phtml') ?>

  </body>
</html>