<?php
/**
9K SPOTTER HELP PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>

	<?php
		echo($this->render('header.phtml'));
	?>

	<div class="row">
		<div>
			<h1>Help</h1>
			<p class='large'>If you have trouble figuring things out, we have added a handy help section to the Spotter.</p>
			<h2>Frequently asked questions</h2>
			<h3>How do I change my details and password?</h3>
			<p class='large'>Please go to <a href='/Code9000/account/edit'>your account page</a> to edit your information.</p>
			<h3>How can the app determine my location?</h3>
			<p class='large'>There are two ways the app can determine your location. If you give your browser permission, you can let the browser determine your geolocation. You can also enter your location in a box, and your location will be determined based on your input.</p>
			<h3>Do I need to upload images when I spot something?</h3>
			<p class='large'>No. Uploading images is completely optional. It is recommended, but entirely optional. Please note that your images are reduced in size.</p>
			<h3>What data is stored in your databases?</h3>
			<p class='large'>Data from your spottings, images associated with spottings, locations, and profile information is stored in the databases. Your password stored in our database, but it is encrypted. Also, city information is stored in the database. You can always <a href='/Code9000/account/delete'>delete your account</a>, but associated spottings and locations are not deleted upon your account deletion.</p>
			<h2>Spotting</h2>
			<p class='large'>You can suggest improvements for a certain location in Ghent.</p>
			<h3>Definition</h3>
			<p>The most basic thing you can do with the 9K Spotter is spot locations. A spotting is a suggestion based on a certain location, something you'd like to see improved. You can suggest an improvement for a current location. For instance, you'd like to see more green in a certain area of Ghent. You can let the people know you want some more green and snap a picture. Once your spotting has been submitted, people can start voting on your proposal.</p>
			<h3>Voting and comments</h3>
			<p>If you like a proposal, you can let people know. If you don't, you can also let people know you don't like it. If you find a silly proposal, you can thumbs it down. You can also leave behind a comment. If you want to, you can always change your comment.</p>
			<h2>City Projects</h2>
			<p class='large'>Sometimes, people representing the city of Ghent might really like a proposal. If they do, they can let you know. </p>
			<p>If enough people like your proposal (a threshold has not been determined), your proposal is submitted to the city of Ghent. The cool thing about this is that they will respond to your proposal through the site, so the people can follow up on the status of projects.</p>
			<h3>9K Builder</h3>
			<p>When a spotting reaches a certain level, it becomes a City Project once it has been accepted. This also opens up the 9K Builder, where you can let your imagination run wild.</p>
			<h3>Sandbox Mode</h3>
			<p>You can let your imagination run wild on City Projects, but also when using the Sandbox. The Sandbox is a special edition of the builder that allows you to go wild in your designs. Just create what you'd like to create, no proposals are attached to this mode. You can also go wild with the character: in Sandbox Mode you can decide e.g. how high he can jump!</p>
		</div>
		</div>
		<footer class='row'>
			<p><a href='http://okfn.be/'>&copy; 2013 OKFN</a>. Some rights reserved. <a href='#'>Developed by 9K.</a></p>
		</footer>
	</div>

	<!-- Grab Google CDN's jQuery, fall back to local if offline -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="scripts/libs/jquery-1.9.1.min.js"><\/script>')</script>

  <!--
  Include gumby.js followed by UI modules.
  Or concatenate and minify into a single file
  <script src="scripts/libs/gumby.js"></script>
  <script src="scripts/libs/ui/gumby.retina.js"></script>
  <script src="scripts/libs/ui/gumby.fixed.js"></script>
  <script src="scripts/libs/ui/gumby.skiplink.js"></script>
  <script src="scripts/libs/ui/gumby.toggleswitch.js"></script>
  <script src="scripts/libs/ui/gumby.checkbox.js"></script>
  <script src="scripts/libs/ui/gumby.radiobtn.js"></script>
  <script src="scripts/libs/ui/gumby.tabs.js"></script>
  <script src="scripts/libs/ui/gumby.navbar.js"></script>
  <script src="scripts/libs/ui/jquery.validation.js"></script>
  <script src="scripts/libs/gumby.init.js"></script>-->

  <script src="scripts/libs/gumby.min.js"></script>
  <script src="scripts/plugins.js"></script>
  <script src="scripts/main.js"></script>

  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->

  </body>
</html>