<?php
/**
9K SPOTTER LEAFLET TEST PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Stefaan Christiaens (stefaan.ch@gmail.com)
*/
?>
<!doctype html>
<html dir="ltr" lang="nl-be">
    <head>
        <!-- CHARACTER ENCODING -->
        <meta charset="UTF-8">
        <!-- LATEST VERSION OF RENDERING ENGINE -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <!-- MOST IMPORTANT SEO FRIENDLY TAG -->
        <title>9KBuilder | LEAFLET TEST</title>
        <!-- OTHER IMPORTANT SEO TAGS -->
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="author" content="Stefaan Christiaens">
        <meta name="copyright" content="">
        <!-- HUMANS.TXT FILE -->
        <link rel="author" type="text/plain" href="humans.txt">
        <!-- MOBILE VIEWPORT -->
        <meta name="viewport" content="width=device-width">
        <!-- LINK MY OWN STYLESHEET -->
        <link rel="stylesheet" href="/Code9000/styles/index.css">
        <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.css" />
        <!--[if lte IE 8]>
            <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.ie.css" />
        <![endif]-->
        <style>
            #map{
                height:180px;
                width: 100%;
            }
        </style>

        <script src="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.js"></script>
    </head>
<body>
<!-- LAYOUT / TYPO / CONTENT -->
 <div id="map"></div>
<!-- BOTTOM SCRIPTS -->
<!-- 1. GRAB GOOGLE'S JQUERY CDN -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- 2. FALLBACK TO LOCAL JQUERY IF CDN NOT ACTIVE -->
<script>window.jQuery || document.write('<script src="_scripts/libs/jquery-2.0.2.js"><\/script>')</script>
<script src="/code9000/scripts/map.js"></script>
</body>
</html>
