<!-- Grab Google CDN's jQuery, fall back to local if offline -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="/code9000/scripts/libs/jquery-1.9.1.min.js"><\/script>')</script>

  <!--
  Include gumby.js followed by UI modules.
  Or concatenate and minify into a single file
  <script src="scripts/libs/gumby.js"></script>
  <script src="scripts/libs/ui/gumby.retina.js"></script>
  <script src="scripts/libs/ui/gumby.fixed.js"></script>
  <script src="scripts/libs/ui/gumby.skiplink.js"></script>
  <script src="scripts/libs/ui/gumby.toggleswitch.js"></script>
  <script src="scripts/libs/ui/gumby.checkbox.js"></script>
  <script src="scripts/libs/ui/gumby.radiobtn.js"></script>
  <script src="scripts/libs/ui/gumby.tabs.js"></script>
  <script src="scripts/libs/ui/gumby.navbar.js"></script>
  <script src="scripts/libs/ui/jquery.validation.js"></script>
  <script src="scripts/libs/gumby.init.js"></script>-->

  <script src="/code9000/scripts/libs/gumby.min.js"></script>
  <script src="/code9000/scripts/plugins.js"></script>
  <script src="/code9000/scripts/main.js"></script>
  <script src="/code9000/scripts/htmlencode.js">
</script>
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->