	<?php
		echo $this->render('header.phtml');
	?>

	<div class="row">		
		<h1>Log In</h1>
		<p class='large'>Please log in with your existing details to start using the service. If you haven't already, <a href='/Code9000/register'>click here to create a new account.</a></p>
		<?php
		if (isset($_SESSION["msg"])){
			echo "<ul><li class='danger alert'>" . $_SESSION["loginmsg"] . "</li></ul>";
			$_SESSION["msg"] = null;
		}
		?>
		<br/>
		<form method="post" action="/code9000/login">
            <div class="row xwide valign">
                <ul class="six columns centered">
                    <li class="field prepend">
                        <span class="adjoined"><i class="icon-mail"></i></span>
                        <input class="email input" type="email" placeholder="Email" name="email" id="email" />
                    </li>
                    <li class="field prepend">
                        <span class="adjoined"><i class="icon-lock"></i></span>
                        <input class="password input" type="password" placeholder="Password" id="password" name="password" />
                    </li>
                    <li class="field">
						<br/>
                        <div class="medium primary btn"><input type="submit" value="Login"></div>
                    </li>
                </ul>
            </div>

        </form>
		<footer class='row'>
			<p><a href='http://okfn.be/'>&copy; 2013 OKFN</a>. Some rights reserved. <a href='#'>Developed by 9K.</a></p>
		</footer>
	</div>

	<!-- Grab Google CDN's jQuery, fall back to local if offline -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="scripts/libs/jquery-1.9.1.min.js"><\/script>')</script>

  <!--
  Include gumby.js followed by UI modules.
  Or concatenate and minify into a single file
  <script src="scripts/libs/gumby.js"></script>
  <script src="scripts/libs/ui/gumby.retina.js"></script>
  <script src="scripts/libs/ui/gumby.fixed.js"></script>
  <script src="scripts/libs/ui/gumby.skiplink.js"></script>
  <script src="scripts/libs/ui/gumby.toggleswitch.js"></script>
  <script src="scripts/libs/ui/gumby.checkbox.js"></script>
  <script src="scripts/libs/ui/gumby.radiobtn.js"></script>
  <script src="scripts/libs/ui/gumby.tabs.js"></script>
  <script src="scripts/libs/ui/gumby.navbar.js"></script>
  <script src="scripts/libs/ui/jquery.validation.js"></script>
  <script src="scripts/libs/gumby.init.js"></script>-->

  <script src="scripts/libs/gumby.min.js"></script>
  <script src="scripts/plugins.js"></script>
  <script src="scripts/main.js"></script>

  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->

  </body>
</html>