	<?php
		echo $this->render('header.phtml');
	?>

	<div class="row">		
		<h1>Log In</h1>
		<p class='large'>Please log in with your existing details to start using the service. If you haven't already, <a href='/Code9000/register'>click here to create a new account.</a></p>
		<br/>
		<form method="post" action="/code9000/login">
            <div class="row xwide valign">
                <ul class="six columns centered">
						<?php
						if (isset($_SESSION["loginmsg"])){
							echo "<ul><li class='danger alert'>" . $_SESSION["loginmsg"] . "</li></ul><br/>";
							$_SESSION["loginmsg"] = null;
						}
						?>
                    <li class="field prepend">
                        <span class="adjoined"><i class="icon-mail"></i></span>
                        <input class="email input" type="email" placeholder="Email" name="email" id="email" />
                    </li>
                    <li class="field prepend">
                        <span class="adjoined"><i class="icon-lock"></i></span>
                        <input class="password input" type="password" placeholder="Password" id="password" name="password" />
                    </li>
                    <li class="field">
						<br/>
                        <div class="medium primary btn"><input type="submit" value="Login"></div>
                    </li>
                </ul>
            </div>

        </form>
		<footer class='row'>
			<p><a href='http://okfn.be/'>&copy; 2013 OKFN</a>. Some rights reserved. <a href='#'>Developed by 9K.</a></p>
		</footer>
	</div>

	<?php echo $this->render('libsfooter.phtml') ?>
  </body>
</html>