<?php
/**
9K SPOTTER REGISTER
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Stefaan Christiaens (stefaan.ch@gmail.com)
*/
?>
<!doctype html>
<html dir="ltr" lang="nl-be">
	<head>
		<!-- CHARACTER ENCODING -->
		<meta charset="UTF-8">
		<!-- LATEST VERSION OF RENDERING ENGINE -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<!-- MOST IMPORTANT SEO FRIENDLY TAG -->
		<title>9K Register</title>
		<!-- OTHER IMPORTANT SEO TAGS -->
		<meta name="description" content="">
		<meta name="keywords" content="">
		<meta name="author" content="">
		<meta name="copyright" content="">
		<!-- HUMANS.TXT FILE -->
		<link rel="author" type="text/plain" href="humans.txt">
		<!-- MOBILE VIEWPORT -->
		<meta name="viewport" content="width=device-width">
		<!-- LINK MY OWN STYLESHEET -->
		<link rel="stylesheet" href="/Code9000/styles/index.css">
	</head>
<body>
<!-- LAYOUT / TYPO / CONTENT -->
<div id="page-wrapper" class="page">
	<nav>
		<ul>
			<li><a href='/Code9000/home'>Home</a></li>
			<li><a href='/Code9000/alerts'>Alerts</a></li>
			<li><a href='/Code9000/tips'>Tips</a></li>
			<li><a href='/Code9000/about'>About</a></li>
		</ul>
	</nav>
	<h1>register</h1>
        <form method="post" action="/code9000/register">
            <input type="email" id="email" name="email" placeholder="email" /><br/>
            <input type="password" id="password" name="password" placeholder="password" /><br/>
            <input type="password" id="passwordre" name="password" placeholder="password again" /><br/>
            <input type="checkbox" id="admin" name="admin" />admin<br/>
            <input type="date" id="dob" name="dob" placeholder="date of birth" /><br/>
            <input type="fname" id="fname" name="fname" placeholder="fname" /><br/>
            <input type="sname" id="sname" name="sname" placeholder="sname" /><br/>
            
            <input type="file" name="file" id="file" />
            <div id="avatar"></div>
            <input type="submit" id="submit" name="submit" value="submit" />
        </form>
</div>
<!-- BOTTOM SCRIPTS -->
<!-- 1. GRAB GOOGLE'S JQUERY CDN -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- 2. FALLBACK TO LOCAL JQUERY IF CDN NOT ACTIVE -->
<script>window.jQuery || document.write('<script src="_scripts/libs/jquery-2.0.2.js"><\/script>')</script>
<script src="/Code9000/scripts/avatarupload.js"></script>
</body>
</html>
