<?php
/**
9K SPOTTER REGISTER
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
Stefaan Christiaens (stefaan.ch@gmail.com)
*/
?>

	<?php
		echo $this->render('header.phtml');
	?>

    <div id="container" class="row">
		<h1>Registration</h1>
		<p class='large'>Please register your account by providing your details so we can store your preferences and spottings in our database. You will be sent an activation email before you can use the service.</p>
		<br/>
        <form method="post" action="/code9000/register">
            <div class="row xwide valign">
                <ul class="seven columns centered">
                    <li class="field prepend">
                        <span class="adjoined"><i class="icon-user"></i></span>
                        <input class="text input" type="text" placeholder="First Name" name="fname" id="fname" />
                    </li>
                    <li class="field prepend">
                        <span class="adjoined"></span>
                        <input class="text input" type="text" placeholder="Last Name" name="sname" id="sname" />
                    </li>
                    <li class="field prepend">
                        <span class="adjoined"><i class="icon-mail"></i></span>
                        <input class="email input" type="email" placeholder="Email" name="email" id="email" />
                    </li>
                    <li class="field prepend">
                        <span class="adjoined"><i class="icon-calendar"></i></span>
                        <input class="date input" type="date" placeholder="Birthday" name="dob" id="dob" />
                    </li>
                    <li class="field prepend">
                        <span class="adjoined"><i class="icon-lock"></i></span>
                        <input class="password input" type="password" placeholder="Password" id="password" name="password" />
                    </li>
                    <li class="field prepend">
                        <span class="adjoined"><i class="icon-lock"></i></span>
                        <input class="password input" type="password" placeholder="Retype password" name="passwordre" id="passwordre" />
                    </li>
                    <li class="field prepend">
                        <span class="adjoined"><i class="icon-camera"></i></span>
                        <label id="fileButton" class="medium primary btn" for="file">Set Avatar...</label>
                        <input class="file input" type="file" value="Set Avatar" id="file" name="file" />
                    </li>
                    <li>
                        <div id="avatar"></div>
                    </li>
                    <li class="field">
                        <label class="checkbox checked" for="admin">
                            <input name="admin" id="admin" value="1" type="checkbox" >
                            <span></span> Admin
                        </label>
                    </li>

                    <li class="field">
                        <div class="medium primary btn" style="width: 100%"><input type="submit" value="Register"></div>
                    </li>
                </ul>
            </div>

        </form>
    </div>


	<?php echo $this->render('libsfooter.phtml') ?>
  <script src="/Code9000/scripts/avatarupload.js"></script>

  </body>
</html>
