<?php
/**
9K SPOTTER HOMEPAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>
<?php
/**
9K SPOTTER ABOUT PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>
<!doctype html>
<html dir="ltr" lang="nl-be">
	<head>
		<!-- CHARACTER ENCODING -->
		<meta charset="UTF-8">
		<!-- LATEST VERSION OF RENDERING ENGINE -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<!-- MOST IMPORTANT SEO FRIENDLY TAG -->
		<title>Spot Something</title>
		<!-- OTHER IMPORTANT SEO TAGS -->
		<meta name="description" content="">
		<meta name="keywords" content="">
		<meta name="author" content="">
		<meta name="copyright" content="">
		<!-- HUMANS.TXT FILE -->
		<link rel="author" type="text/plain" href="humans.txt">
		<!-- MOBILE VIEWPORT -->
		<meta name="viewport" content="width=device-width">
		<!-- LINK MY OWN STYLESHEET -->
		<link rel="stylesheet" href="/Code9000/styles/index.css">
		<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.css" />
	</head>
<body>
<!-- LAYOUT / TYPO / CONTENT -->
<div id="page-wrapper" class="page">
	<nav>
		<ul>
			<li><a href='/Code9000/home'>Home</a></li>
			<li><a href='/Code9000/alerts'>Alerts</a></li>
			<li><a href='/Code9000/tips'>Tips</a></li>
			<li><a href='/Code9000/about'>About</a></li>
		</ul>
	</nav>
	<h1>Spot Something</h1>
	<section id="Spot1">
		<h2>What did you spot?</h2>
		<input id="what" name="what" type="text" required placeholder="What did you spot?">
		<br/>
		<input id="solution" name="solution" type="text" required placeholder="Possible solution?">
	</section>
	<section id="Spot2">
		<h2>Where are you?</h2>
		<input id="location_street" name="location_street" type="text" required placeholder="Type your address here"><button id="streetlocation" name="streetlocation" type="button">Use this address</button>
		<br/>
		<button id="autolocation" name="autolocation" type="button">Use geolocation</button>
		<div id="map"></div>
		<h2>Upload an image for this spot</h2>
		<input type="file" name="img_spot" id="img_spot"><br>
		<div id="spotimg">
			
		</div>
	</section>	
	<section id="Spot3">
		<h2>Upload an image for this location</h2>
		<input type="file" name="img_location" id="img_location"><br>
		<div id="locationimg">
			
		</div>
	</section>
	<br/>
	<br/>
	<button id="confirm" name="confirm" type="button">Confirm spotting</button>
	<button id="cancel" name="cancel" type="button">Cancel spotting</button>
</div>
<style>
	#map{
		height:300px;
		width: 100%;
	}
</style>
<script src="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.js"></script>
<!-- BOTTOM SCRIPTS -->
<!-- 1. GRAB GOOGLE'S JQUERY CDN -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- 2. FALLBACK TO LOCAL JQUERY IF CDN NOT ACTIVE -->
<script>window.jQuery || document.write('<script src="scripts/vendor/jquery-2.0.2.min.js"><\/script>')</script>
<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script src="/Code9000/scripts/spot_create.js"></script>
</body>
</html>