<?php
/**
9K SPOTTER SPOTTINGS PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>
	<?php
		echo($this->render('header.phtml'));
	?>
		<div class='row'>
				<h1>Spottings</h1>
				<p class='large'>Welcome to the spottings page. This is a great starting point for all things about spotting. What is it that you would like to do?</p>
				<div class="row">
					<div class='four columns'>
						<h3>See all spottings</h3>
						<p>Check out a list of spottings all throughout Ghent!</p>
						<div class="medium primary btn icon-left icon-list"><a href="/Code9000/spots">Check out spottings</a></div>
					</div>
					<div class='four columns'>
						<h3>Submit your own feedback</h3>
						<p>Leave your own suggestion behind. How do you want to improve Ghent?</p>
						<div class="medium primary btn icon-left icon-list-add"><a href="/Code9000/spots/create">Spot something</a></div>
					</div>
					<div class='four columns'>
						<h3>Check out your posts</h3>
						<p>Check out how many points your proposals have earned, and how many points your proposals have earned.</p>
						<div class="medium primary btn icon-left icon-comment"><a href="/Code9000/myspots">See my spottings</a></div>
					</div>
				</div>
		</div>
		<footer class='row'>
			<p><a href='http://okfn.be/'>&copy; 2013 OKFN</a>. Some rights reserved. <a href='#'>Developed by 9K.</a></p>
		</footer>
	</div>

	<!-- Grab Google CDN's jQuery, fall back to local if offline -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="scripts/libs/jquery-1.9.1.min.js"><\/script>')</script>

  <!--
  Include gumby.js followed by UI modules.
  Or concatenate and minify into a single file
  <script src="scripts/libs/gumby.js"></script>
  <script src="scripts/libs/ui/gumby.retina.js"></script>
  <script src="scripts/libs/ui/gumby.fixed.js"></script>
  <script src="scripts/libs/ui/gumby.skiplink.js"></script>
  <script src="scripts/libs/ui/gumby.toggleswitch.js"></script>
  <script src="scripts/libs/ui/gumby.checkbox.js"></script>
  <script src="scripts/libs/ui/gumby.radiobtn.js"></script>
  <script src="scripts/libs/ui/gumby.tabs.js"></script>
  <script src="scripts/libs/ui/gumby.navbar.js"></script>
  <script src="scripts/libs/ui/jquery.validation.js"></script>
  <script src="scripts/libs/gumby.init.js"></script>-->

  <script src="scripts/libs/gumby.min.js"></script>
  <script src="scripts/plugins.js"></script>
  <script src="scripts/main.js"></script>

  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->

  </body>
</html>