<?php
/**
9K SPOTTER SPOTTINGS PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Stefaan Christiaens (stefchri)
Nico Verbruggen (nico.verb@gmail.com)
*/
?>
	<?php
		echo($this->render('header.phtml'));
	?>
		<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.css" />
		<div class='row'>
			<h1>Spotting</h1>
			<p class="large" id="spotTitle">Spottings</p>
			<div id="spot">
					
			</div>
			<div id="map"></div>
			<a href="/Code9000/spot/<?php echo $this->data['id'] ?>/edit">Edit</a>
		</div>
				
		</div>
		<footer class='row'>
			<p><a href='http://okfn.be/'>&copy; 2013 OKFN</a>. Some rights reserved. <a href='#'>Developed by 9K.</a></p>
		</footer>
		<script src="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.js"></script>
		
		<?php echo $this->render('libsfooter.phtml') ?>
		<script>
			var spot_id = <?php echo $this->data['id'] ?>;
		</script>
		<script src="/code9000/scripts/spot.js"></script>
	<style>
		#map{
			height:300px !important;
			width: 100% !important;
		}
	</style>
  
	</body>
</html>