<?php
/**
9K SPOTTER SPOTTINGS PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>
	<?php
		echo($this->render('header.phtml'));
	?>
		<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.css" />
		<div class='row'>
				<h1>Your Spottings</h1>
				<p id="status"></p>
				<a href="#mapbutton" id="mapbutton"><i class="icon-map"></i>Show map</a>
				<a href="#listbutton" id="listbutton"><i class="icon-menu"></i>Show list</a>
				<section id="spotlist">
					
				</section>
				<section id="spotmap">
					<div id="map"></div>
				</section>
				<p></p>
		</div>
		<footer class='row'>
			<p><a href='http://okfn.be/'>&copy; 2013 OKFN</a>. Some rights reserved. <a href='#'>Developed by 9K.</a></p>
		</footer>
	</div>


<script src="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.js"></script>
<?php echo $this->render('libsfooter.phtml') ?>
<script src="scripts/spots_user.js"></script>

	<script>
		var _root = "http://" + window.location.host.toString() + "/Code9000/api/users/<?php echo $this->data['id']; ?>/spots";
	</script>
	</body>
</html>