<?php
/**
9K SPOTTER CREATE SPOT
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>
<?php
		echo $this->render('header.phtml');
?>
	<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.css" />
	<div class="row">
	<div id="Spotter">
	<h1>Spot Something</h1>
    <img src="/Code9000/img/context/c-spots.png" class="cImg" alt="Spot something" />
	<section id="Spot1">
		<h2>What did you spot?</h2>
		<div class="row xwide valign">
                <ul class="six columns centered">
                    <li class="field prepend">
                        <span class="adjoined"></span>
                        <input class="input" type="text" placeholder="What did you spot?" name="what" id="what" />
                    </li>
                    <li class="field prepend">
                        <span class="adjoined"></span>
                        <textarea class="input" placeholder="Do you have a possible solution?" id="solution" name="solution"></textarea>
                    </li>
                </ul>
         </div>
	</section>
	<section id="Spot2">
		<h2>Where are you?</h2>
		<div class="row xwide valign">
                <ul class="six columns centered">
                    <li class="field prepend">
                        <span class="adjoined"></span>
                        <input class='input' id="location_street" name="location_street" type="text" required placeholder="Your address">
						
                    </li>
					<li><a id="streetlocation" name="streetlocation">Use this address</a></li>
					<li><a id="autolocation" name="autolocation">Get location</a></li>
                </ul>
         </div>
		
		<div id="map">
			
		</div>
        
		<h2>Upload an image for this spot</h2>
		<input type="file" name="img_spot" id="img_spot"><br>
		<div id="spotimg">
			
		</div>
	</section>
	</div>
    
    <div id="pageActions">
        <button id="cancel" name="cancel" type="button">Cancel</button>
        <button id="confirm" name="confirm" type="submit">Spot</button>
    </div>
</div>
<script src="http://cdn.leafletjs.com/leaflet-0.6.2/leaflet.js"></script>
<!-- BOTTOM SCRIPTS -->
<!-- 1. GRAB GOOGLE'S JQUERY CDN -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- 2. FALLBACK TO LOCAL JQUERY IF CDN NOT ACTIVE -->
<script>window.jQuery || document.write('<script src="scripts/vendor/jquery-2.0.2.min.js"><\/script>')</script>
<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script src="/Code9000/scripts/spot_create.js"></script>
</body>
</html>