<?php
/**
9K SPOTTER SPOTTINGS PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>
	<?php
		echo($this->render('header.phtml'));
	?>
		<div class='row'>
				<h1>Spottings</h1>
				<p class='large'>Welcome to the spottings page. This is a great starting point for all things about spotting. What is it that you would like to do?</p>
				<div class="row">
					<div class='four columns'>
						<h3>See all spottings</h3>
						<p>Check out a list of spottings all throughout Ghent!</p>
						<div class="medium primary btn icon-left icon-list"><a href="/Code9000/spots">Check out spottings</a></div>
					</div>
					<div class='four columns'>
						<h3>Submit your own feedback</h3>
						<p>Leave your own suggestion behind. How do you want to improve Ghent?</p>
						<div class="medium primary btn icon-left icon-list-add"><a href="/Code9000/spots/create">Spot something</a></div>
					</div>
					<div class='four columns'>
						<h3>Check out your posts</h3>
						<p>Check out how many points your proposals have earned, and how many points your proposals have earned.</p>
						<div class="medium primary btn icon-left icon-comment"><a href="/Code9000/myspots">See my spottings</a></div>
					</div>
				</div>
				<div class="row">
					<div class='four columns'>
						<h3>City Proposals</h3>
						<p>Check out official city projects and mandates.</p>
						<div class="medium primary btn icon-left icon-comment"><a href="/Code9000/cityproposals">See city proposals</a></div>
					</div>
					<div class='four columns'>
						<h3>City Projects</h3>
						<p>Check out official city projects and mandates.</p>
						<div class="medium primary btn icon-left icon-comment"><a href="/Code9000/myspots">See city projects</a></div>
					</div>
				</div>
		</div>
		<footer class='row'>
			<p><a href='http://okfn.be/'>&copy; 2013 OKFN</a>. Some rights reserved. <a href='#'>Developed by 9K.</a></p>
		</footer>
	</div>

	<?php echo $this->render('libsfooter.phtml') ?>

  </body>
</html>