<?php
/**
9K SPOTTER ABOUT PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>
<!doctype html>
<html dir="ltr" lang="nl-be">
	<head>
		<!-- CHARACTER ENCODING -->
		<meta charset="UTF-8">
		<!-- LATEST VERSION OF RENDERING ENGINE -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<!-- MOST IMPORTANT SEO FRIENDLY TAG -->
		<title>About 9K</title>
		<!-- OTHER IMPORTANT SEO TAGS -->
		<meta name="description" content="">
		<meta name="keywords" content="">
		<meta name="author" content="">
		<meta name="copyright" content="">
		<!-- HUMANS.TXT FILE -->
		<link rel="author" type="text/plain" href="humans.txt">
		<!-- MOBILE VIEWPORT -->
		<meta name="viewport" content="width=device-width">
		<!-- LINK MY OWN STYLESHEET -->
		<link rel="stylesheet" href="/Code9000/styles/index.css">
	</head>
<body>
<!-- LAYOUT / TYPO / CONTENT -->
<div id="page-wrapper" class="page">
	<nav>
		<ul>
			<li><a href='/Code9000/home'>Home</a></li>
			<li><a href='/Code9000/alerts'>Alerts</a></li>
			<li><a href='/Code9000/tips'>Tips</a></li>
			<li><a href='/Code9000/about'>About</a></li>
		</ul>
	</nav>
	<h1>Tips</h1>
	<section>
		<p>Tips</p>
	</section>
</div>
<!-- BOTTOM SCRIPTS -->
<!-- 1. GRAB GOOGLE'S JQUERY CDN -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- 2. FALLBACK TO LOCAL JQUERY IF CDN NOT ACTIVE -->
<script>window.jQuery || document.write('<script src="_scripts/libs/jquery-2.0.2.js"><\/script>')</script>
</body>
</html>
