<?php
/**
9K SPOTTER HOMEPAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>
<?php
/**
9K SPOTTER ABOUT PAGE
---------
# COPYRIGHT
(c) 2013, OKFN Belgium. Some rights reserved.

# AUTHOR
Nico Verbruggen (nico.verb@gmail.com)
*/
?>
<!doctype html>
<html dir="ltr" lang="nl-be">
	<head>
		<!-- CHARACTER ENCODING -->
		<meta charset="UTF-8">
		<!-- LATEST VERSION OF RENDERING ENGINE -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<!-- MOST IMPORTANT SEO FRIENDLY TAG -->
		<title>Upload A File</title>
		<!-- OTHER IMPORTANT SEO TAGS -->
		<meta name="description" content="">
		<meta name="keywords" content="">
		<meta name="author" content="">
		<meta name="copyright" content="">
		<!-- HUMANS.TXT FILE -->
		<link rel="author" type="text/plain" href="humans.txt">
		<!-- MOBILE VIEWPORT -->
		<meta name="viewport" content="width=device-width">
		<!-- LINK MY OWN STYLESHEET -->
		<link rel="stylesheet" href="/Code9000/styles/index.css">
	</head>
<body>
<!-- LAYOUT / TYPO / CONTENT -->
<div id="page-wrapper" class="page">
	<nav>
		<ul>
			<li><a href='/Code9000/home'>Home</a></li>
			<li><a href='/Code9000/alerts'>Alerts</a></li>
			<li><a href='/Code9000/tips'>Tips</a></li>
			<li><a href='/Code9000/about'>About</a></li>
		</ul>
	</nav>
	<h1>9K Spotter</h1>
	<section>
		<section id="LastFile"></section>
		<h1>Upload a file</h1>
		<p>Below you can add images to the server (up to 2 MB per file). The images will be cropped.</p>
		<label for="file">Filename:</label>
		<input type="file" name="file" id="file" multiple=""><br>
		<section id="UploadedFiles"></section>
	</section>
</div>
<!-- BOTTOM SCRIPTS -->
<!-- 1. GRAB GOOGLE'S JQUERY CDN -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<!-- 2. FALLBACK TO LOCAL JQUERY IF CDN NOT ACTIVE -->
<script>window.jQuery || document.write('<script src="scripts/vendor/jquery-2.0.2.min.js"><\/script>')</script>
<script src="/Code9000/scripts/uploader.js"></script>
</body>
</html>